redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.pe-backstage.local

configs:
  params:
    server.insecure: "true"

server:
  replicas: 1
  extraArgs:
    - --insecure
  ingress:
    enabled: false
