redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.pe-backstage.local

server:
  replicas: 1
  ingress:
    enabled: false
