site_name: 'Python-app'
site_description: 'Main documentation for python-app'
repo_url: https://github.com/yusakh/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'